CC = mpicc
P1_FILES = BellBrandon_HW2-Part1.c
P2_FILES = BellBrandon_HW2-Part2.c
P3_FILES = BellBrandon_HW2-Part3a-Serial.c

all:
	$(CC) -o HW2-Part1 $(P1_FILES)
	$(CC) -o HW2-Part2 $(P2_FILES)
	gcc -o HW2-Part3-Serial $(P3_FILES)

clean:
	rm HW2-Part1 HW2-Part2 HW2-Part3-Serial
