CC = mpicc
P1_FILES = BellBrandon_HW2-Part1.c
P2_FILES = BellBrandon_HW2-Part2.c
P3_FILES = BellBrandon_HW2-Part3-Serial.c

all:
	$(CC) -o HW2-Part1 $(P1_FILES)
	$(CC) -o HW2-Part2 $(P2_FILES)
	$(CC) -o HW2-Part3-Serial $(P2_FILES)

part1:
	$(CC) -o HW2-Part1 $(P1_FILES)

part2:
	$(CC) -o HW2-Part2 $(P2_FILES)

part3:
	$(CC) -o HW2-Part3-Serial $(P2_FILES)

clean:
	rm HW2-Part1 HW2-Part2 HW2-Part3-Serial
