#!/bin/bash  
#SBATCH --job-name="PingPong-Large-Double-Node"  
#SBATCH --output="PingPong-Large-Double-Node.%j.%N.out"  
#SBATCH --partition=compute 
#SBATCH --nodes=2  
#SBATCH --ntasks-per-node=1  
#SBATCH --export=ALL  
#SBATCH -t 00:02:00  
#SBATCH -A ncr119

ibrun ./PingPong-Large
