#!/bin/bash  
#SBATCH --job-name="PingPong-Large-Single-Node"  
#SBATCH --output="PingPong-Large-Single-Node.%j.%N.out"  
#SBATCH --partition=shared 
#SBATCH --nodes=1  
#SBATCH --ntasks-per-node=2  
#SBATCH --export=ALL  
#SBATCH -t 00:05:00  
#SBATCH -A ncr119

ibrun ./PingPong-Large
